/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlesmarttool2.GUI.components;

import littlesmarttool2.model.Channel;

/**
 *
 * @author Rasmus
 */
public class ChannelTabPanel extends javax.swing.JPanel {
    private Channel channel;
    /**
     * Creates new form ChannelTabPanel
     */
    public ChannelTabPanel() {
        initComponents();
    }
    
    public void setChannel(Channel channel)
    {
        this.channel = channel;
        channelSettingViewer1.updateBounds(channel.getCalibLow(), channel.getCalibHigh());
        channelSettingViewer1.setBlockList(channel.getSetting().getBlocks());
        channelSettingViewer1.setThresholdlist(channel.getSetting().getThresholds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        channelSettingViewer1 = new littlesmarttool2.GUI.components.ChannelSettingViewer();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout channelSettingViewer1Layout = new javax.swing.GroupLayout(channelSettingViewer1);
        channelSettingViewer1.setLayout(channelSettingViewer1Layout);
        channelSettingViewer1Layout.setHorizontalGroup(
            channelSettingViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        channelSettingViewer1Layout.setVerticalGroup(
            channelSettingViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(channelSettingViewer1, java.awt.BorderLayout.NORTH);

        jLabel1.setText("Config here");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private littlesmarttool2.GUI.components.ChannelSettingViewer channelSettingViewer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
