/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlesmarttool2.GUI.components;

import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;
import littlesmarttool2.model.*;

/**
 *
 * @author marcher89
 */
public class ConnectionTypeBox extends javax.swing.JPanel {

    private ConnectionType connectionType;
    
    /**
     * Creates new form ConnectionTypeBox
     */
    public ConnectionTypeBox(ConnectionType connetionType) {
        this.connectionType = connetionType;
        
        initComponents();
        
        switch(connetionType){
            case IR:
                radioButton.setText("IR");
                description.setText("This is IR.");
                break;
            case Wire:
                radioButton.setText("Wire");
                description.setText("This is wire.");
                break;
            case LANC:
                radioButton.setText("LANC");
                description.setText("This is LANC.");
                break;
        }
    }
    
    public ConnectionType getConnectionType() {
        return connectionType;
    }

    @Override
    public void setEnabled(boolean b){
        super.setEnabled(b);
        radioButton.setEnabled(b);
        description.setEnabled(b);
    }
    
    public boolean isSelected() {
        return radioButton.isSelected();
    }
    
    public void setSelected(boolean b) {
        radioButton.setSelected(b);
    }

    public void addToGroup(ButtonGroup group) {
        group.add(radioButton);
    }
    
    public void addItemListener(ItemListener itemListener) {
        radioButton.addItemListener(itemListener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButton = new javax.swing.JRadioButton();
        description = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1200, 39));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        radioButton.setText("jRadioButton1");
        add(radioButton);

        description.setLabelFor(radioButton);
        description.setText("jLabel1");
        add(description);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JRadioButton radioButton;
    // End of variables declaration//GEN-END:variables


  

    
}
