/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlesmarttool2.GUI.components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Rasmus
 */
public class NWayInputViewer extends InputViewer {

    private int n = 1;
    
    /**
     * Must be greater than 0!
     * @param n 
     */
    public void setN(int n)
    {
        this.n = n;
        repaint();
    }
    
    /**
     * 0 to (n-1)
     */
    private int getValueBlock()
    {
        double prblock = 1.0 / n;
        double value = getValuePct();
        for (int i = 0; i < n; i++)
        {
            if (value >= (prblock * i) && value < (prblock * (i+1)))
                    return i;
        }
        //Just in case
        if (value <= 0) return 0;
        return n-1;
    }
    
    /**
     * Creates new form NWayInputViewer
     */
    public NWayInputViewer() {
        initComponents();
    }

    //private void getBox
    
    @Override
    public void paintComponent(Graphics g)
    {
        Graphics2D g2 = (Graphics2D) g;
        
        g2.setColor(Color.white);
        g2.fillRect(0, 0, getWidth(), getHeight());
        int widthPrBox = (getWidth() / n);
        int height = getHeight();
        int selection = getValueBlock();
        for (int i = 0; i < n; i++)
        {
            int x = widthPrBox * i;
            if (i == selection)
            {
                g2.setColor(Color.green);
                g2.fillRect(x, 0, widthPrBox-4, height-1);
            }
            g2.setColor(Color.black);
            g2.drawRect(x, 0, widthPrBox-4, height-1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
