/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlesmarttool2.GUI.components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Rasmus
 */
public class PushbuttonInputViewer extends InputViewer {
    
    /**
     * Creates new form PushbuttonInputViewer
     */
    public PushbuttonInputViewer() {
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setColor(Color.white);
        g2.fillRect(0, 0, getWidth(), getHeight());
        int dim = Math.min(getWidth()-1,getHeight()-1);
        dim = Math.min(dim, 50); //Max 50 px
        //Pressed
        if (getValuePct() > .5)
        {
            g2.setColor(Color.green);
            g2.fillOval((getWidth()/2) - (dim/2), (getHeight()/2) - (dim/2), dim, dim);
        }
        //Border & lines
        g2.setColor(Color.black);
        //g2.fillOval((getWidth()/2) - (dim/2)) / 2, (getHeight()/2) - (dim/2) / 2, dim/2, dim/2);
        g2.drawOval((getWidth()/2) - (dim/2), (getHeight()/2) - (dim/2), dim, dim);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
