/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlesmarttool2.GUI.components;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
/**
 *
 * @author Rasmus
 */
public class StickInputViewer extends InputViewer {
    
    private static BasicStroke readingStroke = new BasicStroke(2.0f, BasicStroke.CAP_BUTT,
                        BasicStroke.JOIN_MITER, 10.0f);
    
    private final int arrowSize = 7;
    
    private int getValuePosition()
    {
        return (int)(getValuePct() * getWidth());
    }
    
    /**
     * Creates new form StickInputViewer
     */
    public StickInputViewer() {
        initComponents();
    }

    private Polygon getBottomArrow(int x)
    {
        int[] xpoints = new int[3], ypoints = new int[3];
        int bottom = getHeight();
        xpoints[0] = x - (arrowSize+1);
        xpoints[1] = x;
        xpoints[2] = x + (arrowSize+1);
        ypoints[0] = bottom;
        ypoints[1] = bottom - (arrowSize+1);
        ypoints[2] = bottom;
        return new Polygon(xpoints, ypoints, 3);
    }
    
    private Polygon getTopArrow(int x)
    {
        int[] xpoints = new int[3], ypoints = new int[3];
        int top = 0;
        xpoints[0] = x - arrowSize;
        xpoints[1] = x;
        xpoints[2] = x + arrowSize;
        ypoints[0] = top;
        ypoints[1] = top + arrowSize;
        ypoints[2] = top;
        return new Polygon(xpoints, ypoints, 3);
    }
    
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        //Clear
        g2.setColor(new Color(240,240,240));
        g2.fillRect(0, 0, getWidth(), getHeight());
        
        g2.setStroke(readingStroke);
        
        //Draw current value
        g2.setColor(Color.black);
        g2.drawLine(getValuePosition(), 0, getValuePosition(), getHeight());
        g2.fillPolygon(getBottomArrow(getValuePosition()));
        g2.fillPolygon(getTopArrow(getValuePosition()));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
