/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlesmarttool2.GUI;
import javax.swing.DefaultListModel;
import littlesmarttool2.model.IRCommand;
import littlesmarttool2.model.ModelUtil;

/**
 *
 * @author Rasmus
 */
public class IRManageDialog extends javax.swing.JDialog {

    SS2Wizard wizard;
    DefaultListModel commandListModel = new DefaultListModel();
    /**
     * Creates new form IRManageDialog
     */
    public IRManageDialog(java.awt.Frame parent, SS2Wizard wizard) {
        super(parent, true);
        initComponents();
        this.wizard = wizard;
        cameraLabel.setText(wizard.getConfiguration().getCameraModel().getIdentifier());
        for (IRCommand command : wizard.getConfiguration().getCameraModel().getCustomIRCommands())
            commandListModel.addElement(command);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        recordNewButton = new javax.swing.JButton();
        selectedPanel = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        commandList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cameraLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(423, 316));

        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        buttonPanel.setLayout(new java.awt.BorderLayout());

        recordNewButton.setText("Record new");
        recordNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordNewButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(recordNewButton, java.awt.BorderLayout.PAGE_START);

        selectedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected command"));
        selectedPanel.setEnabled(false);
        selectedPanel.setMaximumSize(new java.awt.Dimension(120, 80));
        selectedPanel.setMinimumSize(new java.awt.Dimension(120, 18));
        selectedPanel.setPreferredSize(new java.awt.Dimension(120, 80));
        selectedPanel.setLayout(new java.awt.GridLayout(0, 1));

        editButton.setText("Edit");
        editButton.setEnabled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        selectedPanel.add(editButton);

        deleteButton.setText("Delete");
        deleteButton.setEnabled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        selectedPanel.add(deleteButton);

        buttonPanel.add(selectedPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.LINE_END);

        commandList.setModel(commandListModel);
        commandList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                commandListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(commandList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Custom IR commands for");
        jPanel1.add(jLabel1);

        cameraLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cameraLabel.setText("(camera model)");
        jPanel1.add(cameraLabel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(closeButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void recordNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordNewButtonActionPerformed
        IRRecordDialog diag = new IRRecordDialog(wizard, wizard.getConfiguration().getCameraModel(), wizard.getSerialController());
        diag.setVisible(true);
        if (diag.getResult() != null)
            commandListModel.addElement(diag.getResult());
    }//GEN-LAST:event_recordNewButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        IRRecordDialog diag = new IRRecordDialog(wizard, wizard.getConfiguration().getCameraModel(), wizard.getSerialController(),(IRCommand)commandList.getSelectedValue());
        diag.setVisible(true);
        commandList.repaint();
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        ModelUtil.deleteCustomIRCommand((IRCommand)commandList.getSelectedValue());
        commandListModel.removeElement(commandList.getSelectedValue());
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void commandListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_commandListValueChanged
        if (commandList.getSelectedValue() != null)
        {
            selectedPanel.setEnabled(true);
            editButton.setEnabled(true);
            deleteButton.setEnabled(true);
        }
        else
        {
            selectedPanel.setEnabled(false);
            editButton.setEnabled(false);
            deleteButton.setEnabled(false);
        }
    }//GEN-LAST:event_commandListValueChanged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel cameraLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JList commandList;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recordNewButton;
    private javax.swing.JPanel selectedPanel;
    // End of variables declaration//GEN-END:variables
}
