/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlesmarttool2.GUI;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import gnu.io.NoSuchPortException;
import gnu.io.PortInUseException;
import gnu.io.UnsupportedCommOperationException;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.plaf.metal.MetalLookAndFeel;
import littlesmarttool2.comm.ConnectionListener;
import littlesmarttool2.comm.ResponseListener;
import littlesmarttool2.comm.SerialCommand;
import littlesmarttool2.comm.SerialController;
import littlesmarttool2.model.Configuration;

/**
 *
 * @author marcher89
 */
public class SS2Wizard extends javax.swing.JFrame implements ActionListener{

    private StepPanel[] stepPanels;
    private int currentStep = -1;
    private boolean hasUploaded = false;
    private Configuration configuration;
    private SerialController controller;
    private final String selectPortMsg = "Select port:";
    public boolean shouldStartServoPuller = false;
    private Timer servoPullerTimer = new Timer(50, null);
    private ArrayList<ResponseListener> servoReadingListeners = new ArrayList<>();
    
    /**
     * Creates new form SS2Wizard
     */
    public SS2Wizard() {
        
        try {
            UIManager.setLookAndFeel(new MetalLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {}
        try {
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {}
        initComponents();
        
        
        configuration = new Configuration();
        controller = new SerialController();
        
        //Initialize port chooser
        refreshPortList();
        
        //Initialize step panels
        stepPanels = new StepPanel[]{new Step1Panel(this), new Step2Panel(this), new Step3Panel(this), new Step4Panel(this)};
        
        for (StepPanel step : stepPanels) {
            cardPanel.add(step, step.getName());
        }
        servoReadingListeners.add((ResponseListener)stepPanels[1]);
        servoReadingListeners.add((ResponseListener)stepPanels[2]);
        servoReadingListeners.add((ResponseListener)stepPanels[3]);

        controller.addConnectionListener(new ConnectionListener() {
            @Override
            public void connectionStateChanged(boolean connected) {
                if (!connected)
                {
                    connectedLabel.setText("Not connected");
                    portChooser.setSelectedIndex(0);
                }
            }
        });
        
        servoPullerTimer.addActionListener(this);
        goToStep(0);
    }
    
    public void stopAutoServoPulling()
    {
        servoPullerTimer.stop();
    }
    
    public void startAutoServoPulling()
    {
        servoPullerTimer.start();
        System.out.println("Starting auto servo pulling");
    }
    
    public Configuration getConfiguration(){
        return configuration;
    }
    
    public SerialController getSerialController(){
        return controller;
    }
    
    public void setHasUploaded(boolean hasUploaded){
        this.hasUploaded = hasUploaded;
    }
    
    public boolean getHasUploaded(){
        return hasUploaded;
    }
    
    public void setBackEnabled(boolean val) { backButton.setEnabled(val);}
    
    public void setNextEnabled(boolean val) { nextButton.setEnabled(val);}
    
    private void goToStep(int index) {
        backButton.setEnabled((index <= 0) ? false : true);
        nextButton.setEnabled(true);
        
        nextButton.setText((index >= stepPanels.length-1) ? "Close" : "Next");
        if(currentStep > -1) stepPanels[currentStep].onHide();
        ((CardLayout)cardPanel.getLayout()).show(cardPanel, stepPanels[index].getName());
        stepPanels[index].onDisplay();
        
        headline.setText(stepPanels[index].getName());
        currentStep = index;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        headline = new javax.swing.JLabel();
        portPanel = new javax.swing.JPanel();
        portLabel = new javax.swing.JLabel();
        portChooser = new javax.swing.JComboBox();
        refreshPortListButton = new javax.swing.JButton();
        connectedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StratoSnapper 2");
        setMinimumSize(new java.awt.Dimension(750, 570));
        setPreferredSize(new java.awt.Dimension(750, 570));

        contentPanel.setPreferredSize(new java.awt.Dimension(100, 700));
        contentPanel.setLayout(new java.awt.BorderLayout());

        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        buttonPanel.setLayout(new java.awt.BorderLayout());

        backButton.setText("Back");
        backButton.setActionCommand("");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(backButton, java.awt.BorderLayout.WEST);

        nextButton.setText("Next");
        nextButton.setActionCommand("");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(nextButton, java.awt.BorderLayout.EAST);

        contentPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        cardPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        cardPanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(cardPanel, java.awt.BorderLayout.CENTER);

        upperPanel.setLayout(new java.awt.BorderLayout());

        headline.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        headline.setText("StratoSnapper 2");
        headline.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        upperPanel.add(headline, java.awt.BorderLayout.CENTER);

        portPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        portPanel.setLayout(new javax.swing.BoxLayout(portPanel, javax.swing.BoxLayout.LINE_AXIS));

        portLabel.setText("Choose port:");
        portLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        portPanel.add(portLabel);

        portChooser.setMaximumSize(new java.awt.Dimension(32767, 21));
        portChooser.setPreferredSize(new java.awt.Dimension(150, 20));
        portChooser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                portChooserItemStateChanged(evt);
            }
        });
        portPanel.add(portChooser);

        refreshPortListButton.setText("Refresh");
        refreshPortListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPortListButtonActionPerformed(evt);
            }
        });
        portPanel.add(refreshPortListButton);

        connectedLabel.setText("Not connected");
        connectedLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        connectedLabel.setMaximumSize(new java.awt.Dimension(110, 14));
        connectedLabel.setMinimumSize(new java.awt.Dimension(110, 14));
        connectedLabel.setPreferredSize(new java.awt.Dimension(110, 14));
        portPanel.add(connectedLabel);

        upperPanel.add(portPanel, java.awt.BorderLayout.EAST);

        contentPanel.add(upperPanel, java.awt.BorderLayout.NORTH);

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        goToStep(currentStep-1);
    }//GEN-LAST:event_backButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if(currentStep < stepPanels.length-1)
            goToStep(currentStep+1);
        else{
            if(hasUploaded || JOptionPane.showConfirmDialog(this, "Your configuration has not been uploaded to the StratoSnapper2.\nAre you sure, you want to quit?", "Really quit?", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.YES_OPTION)
            System.exit(0);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void portChooserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_portChooserItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED)
        {
            controller.disconnect();
            return;
        }
        if (evt.getItem() == selectPortMsg) return;
        
        try {
            connectedLabel.setText("Connecting...");
            SerialCommand connect = controller.connect(evt.getItem().toString(),15000); //TODO: Other thread
            int[] v = connect.convertArgsToInt();
            connectedLabel.setText("Connected (v. " + v[1] + "." + v[2] + ")");
            servoPullerTimer.start();
        } catch (NoSuchPortException ex) {
            Logger.getLogger(SS2Wizard.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "The selected port is invalid.\r\nEnsure that you selected the right port or try to connect the Stratosnapper to another port","Invalid port", JOptionPane.ERROR_MESSAGE);
            refreshPortList();
        } catch (PortInUseException ex) {
            Logger.getLogger(SS2Wizard.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "The selected port is in use.\r\nEnsure that you selected the right port, and that no other software is using it.\r\nOn Mac computers, this can happen as a result of fault in the serial driver. To solve this, run the following commands:\r\nmkdir /var/lock\r\nchmod 777 /var/lock","Port in use", JOptionPane.ERROR_MESSAGE);
        } catch (UnsupportedCommOperationException | IOException ex) {
            Logger.getLogger(SS2Wizard.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "An error occured while connecting to the Stratosnapper.\r\nPlease try again or use another port if the error persists\r\nMessage from system: \"" + ex.getMessage() + "\"","Connection error", JOptionPane.ERROR_MESSAGE);
        } catch (TimeoutException ex) {
            Logger.getLogger(SS2Wizard.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Unable to connect to StratoSnapper.\r\nEnsure that you selected the right port.","Connection timed out", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_portChooserItemStateChanged

    private void refreshPortList()
    {
        ArrayList<String> portNames = SerialController.getPortNames();
        portChooser.removeAllItems();
        portNames.add(0, selectPortMsg);
        portChooser.setModel(new DefaultComboBoxModel(portNames.toArray()));
    }
    
    private void refreshPortListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPortListButtonActionPerformed
        refreshPortList();
    }//GEN-LAST:event_refreshPortListButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel connectedLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel headline;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox portChooser;
    private javax.swing.JLabel portLabel;
    private javax.swing.JPanel portPanel;
    private javax.swing.JButton refreshPortListButton;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

    public void receiveResponse(char command, String[] args) {
        if (command != 'V') return;
        if (args.length < 8) return;
        String type = args[0];
        String mainVersion = args[1];
        String subVersion = args[2];
        String year = args[3];
        String month = args[4];
        String day = args[5];
        String hour = args[6];
        String min = args[7];
        connectedLabel.setText(String.format("Connected! (v. %s.%s)",mainVersion,subVersion));
        Logger.getLogger(SS2Wizard.class.getName()).log(Level.INFO, "Connected to Stratosnapper2. Firmware version: {0}.{1} Built:{2}/{3}/{4} {5}:{6}",new String[]{mainVersion,subVersion,year,month,day,hour,min});
        
        shouldStartServoPuller = false;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            //Servo puller timer tick
            System.out.println("Pulling servo value");
            String reading = controller.send("S", 150);
            System.out.println("Pulled servo value");
            SerialCommand cmd = SerialCommand.fromMessage(reading);
            if (cmd.getCommand() != 'S') throw new IOException("Unexpected answer from device");
            System.out.println("Invoking listeners");
            for (ResponseListener l : servoReadingListeners)
                if (l != null)
                    l.receiveResponse(cmd.getCommand(), cmd.getArgs());
        } catch (IOException ex) {
            servoPullerTimer.stop();
            controller.disconnect();
            connectedLabel.setText("Not connected");
            portChooser.setSelectedIndex(0);
        } catch (TimeoutException ex) {
            System.out.println("Timeout! :(");
        }
        
    }
}
