/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlesmarttool2.GUI;

import javax.swing.*;
import littlesmarttool2.model.*;
import littlesmarttool2.util.*;

/**
 *
 * @author marcher89
 */
public class Step1Panel extends StepPanel {
    private SS2Wizard wizard;

    /**
     * Creates new form Step1Panel
     */
    public Step1Panel(SS2Wizard wizard) {
        super(wizard);
        initComponents();
        
        CameraBrand[] brands = JSON.readObjectFromFile("camera-list.json", CameraBrand[].class);
        
        DefaultListModel model = new DefaultListModel();
        for (CameraBrand cameraBrand : brands) {
            model.addElement(cameraBrand);
        }
        brandList.setModel(model);
    }
    
    @Override
    public void onDisplay() {
        //TODO: Do anything??
    }

    @Override
    public void onHide() {
        //TODO: Do anything??
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        brandList = new javax.swing.JList();

        setName("Choose camera and output type"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(brandList);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList brandList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
