/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package littlesmarttool2.GUI;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.RenderingHints;

/**
 *
 * @author Rasmus
 */
public class StickInputViewer extends javax.swing.JPanel {

    private double value = .5;
    
    public void setValue(double value)
    {
        this.value = value;
    }
    
    private int getValuePosition()
    {
        return (int)(value * getWidth());
    }
    
    /**
     * Creates new form StickInputViewer
     */
    public StickInputViewer() {
        initComponents();
    }

    private Polygon getBottomArrow()
    {
        int[] xpoints = new int[3], ypoints = new int[3];
        int bottom = getHeight()-1;
        xpoints[0] = getValuePosition() - 5;
        xpoints[1] = getValuePosition();
        xpoints[2] = getValuePosition() + 5;
        ypoints[0] = bottom;
        ypoints[1] = bottom - 5;
        ypoints[2] = bottom;
        return new Polygon(xpoints, ypoints, 3);
    }
    
    private Polygon getTopArrow()
    {
        int[] xpoints = new int[3], ypoints = new int[3];
        int top = 1;
        xpoints[0] = getValuePosition() - 5;
        xpoints[1] = getValuePosition();
        xpoints[2] = getValuePosition() + 5;
        ypoints[0] = top;
        ypoints[1] = top + 5;
        ypoints[2] = top;
        return new Polygon(xpoints, ypoints, 3);
    }
    
    
    @Override
    public void paintComponent(Graphics g)
    {
        Graphics2D g2 = (Graphics2D) g;

        //Draw border
        g2.setColor(Color.white);
        g2.fillRect(0, 0, getWidth(), getHeight());
        g2.setColor(Color.black);
        g2.drawRect(0,0,getWidth()-1, getHeight()-1);
        
        //Draw current value
        g2.setColor(Color.BLACK);
        g2.drawLine(getValuePosition(), 0, getValuePosition(), getHeight());
        g2.fillPolygon(getBottomArrow());
        g2.fillPolygon(getTopArrow());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
